### ISSUE TITLE
Qualitative analysis

### ISSUE THREAD

**Issue by 1822913** [xiph/LPCNet#188]
What are good ways of assessing quality achieved by the LPCNet Vocoder? I found that PESQ results are way worse than the quality I experienced myself, with ratings constantly in the range between 1 and 2 (which is to be interpreted as hardly/barely understandable). Has anyone experienced similar problems with PESQ? What are the alternatives?

**Comment by jmvalin** [comment]
PESQ is useless for vocoders in general, but there's an ancient quality assessment tool that does a good job. I believe it's called "ears" :-) Seriously, subjective listening is really the only decent way I've found to evaluate vocoders. I've not come across any remotely useful objective metric.

**Comment by 1822913** [comment]
Thank you for taking the time to answer!
